apiVersion: v2
name: jc-kubescale
description: JC-KubeScale AI - Kubernetes-native AI Inference & Autoscaling Platform
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - name: JC-KubeScale Team
    email: team@jc-kubescale.ai