apiVersion: v1
kind: Service
metadata:
  name: jc-kubescale-api
  namespace: jc-kubescale
  labels:
    app: jc-kubescale-api
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      name: http
  selector:
    app: jc-kubescale-api